<div class="card shadow-sm border-0 mb-4" style="border-radius: 12px;">
    <div class="card-header bg-white border-0 pt-4 pb-2 d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center gap-3">
            <div class="rounded-circle d-flex align-items-center justify-content-center bg-soft-info text-info" style="width: 45px; height: 45px;">
                <i class="las la-map-marked-alt fs-24"></i>
            </div>
            <div>
                <h5 class="mb-0 fw-bold text-dark fs-18">Area Sales Ledger</h5>
                <p class="text-muted small mb-0">Consignments and direct sales generated by field sales representatives across regional areas</p>
            </div>
        </div>
        <span class="badge bg-light text-dark border px-3 py-2 rounded-pill fw-bold">7 Accounts</span>
    </div>
    <div class="card-body pt-2">
        <div class="row g-3 mb-4">
            
            <!-- Sales Representative -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Sales Representative Performance', document.getElementById('salesRepsTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Sales Representative</h6>
                            <span class="text-muted small">Field reps sales ledger</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱{{ number_format($areaRepSales, 2) }}</h5>
                    </div>
                </div>
            </div>

            <!-- Province -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Provincial Sales Ledger', document.getElementById('provincesTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Province</h6>
                            <span class="text-muted small">Sales value by geographic province</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

            <!-- Customer -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Area Sales Customers', document.getElementById('areaCustomersTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Customer</h6>
                            <span class="text-muted small">Active regional school & parish clients</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

            <!-- Collection Status -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Collection Status Tracker', document.getElementById('collectionStatusTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Collection Status</h6>
                            <span class="text-muted small">Consignment settlement collections</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

            <!-- Returned Books -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Returned Books Ledger', document.getElementById('areaReturnsTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Returned Books</h6>
                            <span class="text-muted small">Accrued field consignment returns</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

            <!-- Unsold Inventory -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Unsold Consignment Inventory Valuation', document.getElementById('unsoldConsignmentTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Unsold Inventory</h6>
                            <span class="text-muted small">Valuation of inventory on field consignment</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

            <!-- Commission -->
            <div class="col-md-6 col-xl-4">
                <div class="card border-0 shadow-sm hover-row" style="background-color: #fafafa; border-radius: 10px; border-left: 4px solid #17a2b8 !important; cursor: pointer;" onclick="showSalesLedgerModal('Sales Commissions Accrued', document.getElementById('commissionsTemplate').innerHTML)">
                    <div class="card-body p-3 d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="mb-0 fw-bold text-dark fs-14">Commission</h6>
                            <span class="text-muted small">Accrued field representative commissions</span>
                        </div>
                        <h5 class="mb-0 fw-bold text-dark fs-15">₱0.00</h5>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- TEMPLATE CONTAINER - SALES REPRESENTATIVES -->
<div id="salesRepsTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Rep Name</th>
                    <th>Region Assigned</th>
                    <th class="text-end">Sales Target</th>
                    <th class="text-end">Actual Sales</th>
                    <th class="text-end">Accrued Commission</th>
                </tr>
            </thead>
            <tbody>
                @forelse($areaOrders as $order)
                <tr>
                    <td><span class="fw-bold text-dark">{{ optional($order->areaSalesStaff)->name ?? (optional($order->createdBy)->name ?? 'Field Sales Rep') }}</span></td>
                    <td>{{ optional($order->customer)->customer_name ?? (optional($order->customer)->company_name ?? 'Regional Consignment Area') }}</td>
                    <td class="text-end"><span class="badge bg-light text-dark border">{{ strtoupper($order->type) }}</span></td>
                    <td class="text-end text-success fw-bold">₱{{ number_format($order->total_amount, 2) }}</td>
                    <td class="text-end fw-bold text-dark">₱{{ number_format($order->total_amount * 0.03, 2) }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="5" class="text-center py-4 text-muted">No sales representative logs found in the database.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - PROVINCES -->
<div id="provincesTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Province</th>
                    <th>Region</th>
                    <th class="text-center">Consignment Accounts</th>
                    <th class="text-end">Total Sales</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="4" class="text-center py-4 text-muted">No provincial consignment sales records found in the database.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - CUSTOMERS -->
<div id="areaCustomersTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Customer Name</th>
                    <th>Province</th>
                    <th>Rep Assigned</th>
                    <th>Collection Terms</th>
                    <th class="text-end">Balance</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="text-center py-4 text-muted">No area sales customer accounts found in the database.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - COLLECTION STATUS -->
<div id="collectionStatusTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Consignment Reference</th>
                    <th>Customer</th>
                    <th>Invoice Date</th>
                    <th>Age</th>
                    <th>Status</th>
                    <th class="text-end">Consigned Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="6" class="text-center py-4 text-muted">No collections recorded in the database.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - RETURNED BOOKS -->
<div id="areaReturnsTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Ref No</th>
                    <th>Consignment Account</th>
                    <th>Return Date</th>
                    <th>Copies Returned</th>
                    <th>Reason</th>
                    <th class="text-end">Value Credited</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="6" class="text-center py-4 text-muted">No return logs recorded in the database.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - UNSOLD INVENTORY -->
<div id="unsoldConsignmentTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Book Title</th>
                    <th>Consigned To</th>
                    <th class="text-center">Consigned Qty</th>
                    <th class="text-end">Unit Cost</th>
                    <th class="text-end">Total Inventory Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="text-center py-4 text-muted">No unsold consignment inventory reported.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- TEMPLATE CONTAINER - COMMISSION -->
<div id="commissionsTemplate" style="display: none;">
    <div class="table-responsive">
        <table class="table table-hover align-middle">
            <thead class="table-light text-muted small text-uppercase">
                <tr>
                    <th>Rep Name</th>
                    <th>Evaluation Period</th>
                    <th class="text-end">Sales Settled</th>
                    <th class="text-center">Commission Rate</th>
                    <th class="text-end">Accrued Payout</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="text-center py-4 text-muted">No accrued commission payouts recorded.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
